### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by rlems** [uts-magic-lab/gulp-google-drive#1]
I'm getting **TypeError: undefined is not a function** on drive.src(). node_modules/gulp-google-drive exists with all its dependencies, and so does index.js with the src() function. This is my setup:

```
var config = {
    clientId: '*****.apps.googleusercontent.com',
    clientSecret: '*****',
    refreshToken: '*****'
};
var drive = require('gulp-google-drive', config);

gulp.task('fetch-assets', function(done) {
    **drive.src('*****')**
        .pipe(cached('assets'))
        .pipe(drive.fetch)
        .pipe(remember('assets'))
        .pipe(gulp.dest('public/'))
});
```

Also, when i execute your test script I get the following error:

```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid_grant
  at Request._callback (/Applications/XAMPP/xamppfiles/htdocs/CCV_handhavingskompas/trunk/frontend/node_modules/gulp-google-drive/node_modules/googleapis/node_modules/google-auth-library/lib/transporters.js:78:15)
  at Request.self.callback (/Applications/XAMPP/xamppfiles/htdocs/CCV_handhavingskompas/trunk/frontend/node_modules/gulp-google-drive/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:198:22)
  at Request.emit (events.js:110:17)
  at Request.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/CCV_handhavingskompas/trunk/frontend/node_modules/gulp-google-drive/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:1057:14)
  at Request.emit (events.js:129:20)
  at IncomingMessage.<anonymous> (/Applications/XAMPP/xamppfiles/htdocs/CCV_handhavingskompas/trunk/frontend/node_modules/gulp-google-drive/node_modules/googleapis/node_modules/google-auth-library/node_modules/request/request.js:1003:12)
  at IncomingMessage.emit (events.js:129:20)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by jjclark1982** [comment]
I'm investigating this and I see that the `invalid_grant` message appears when googleapis receives an invalid `refreshToken`. I will write better error messages for this module.

If you are trying to use an access token that expires, you should use it to get a refresh token by following the offline access instructions [here](https://developers.google.com/identity/protocols/OAuth2WebServer#offline) (one time only).
